site_name: TDIP
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference: tdip.md
  - Example: example.ipynb
# theme: readthedocs
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  - mknotebooks:
      execute: false
      title: Example